version: "3"
services:

  mssql:
    build:
      context: ./src/db/build
      args:
        sapw: ${DB_SA_PW}
    ports:
      - 1433:1433
    volumes:
      - leaf-mssql:/var/opt/mssql
    networks:
      local:
        aliases:
          - mssql

  coreapi:
    build:
      context: ./src/server
    ports:
      - 5001:5001
    depends_on:
      - mssql
    volumes:
      - ./src/server:/app
      - ${KEYS}:/.keys
    environment:
      LEAF_JWT_CERT: ${JWT_CERT}
      LEAF_JWT_KEY: ${JWT_KEY}
      LEAF_JWT_KEY_PW: ${JWT_KEY_PW}
      LEAF_APP_DB: ${APP_DB}
      LEAF_CLIN_DB: ${CLIN_DB}
    networks:
      local:
        aliases:
          - coreapi

  node:
    build:
      context: ./src/ui-client
    ports:
      - 3000:3000
    depends_on:
      - coreapi
    volumes:
      - ./src/ui-client:/app
    networks:
      local:
        aliases:
          - node

volumes:
  leaf-mssql:

networks:
  local:
    driver: bridge
