version: "3"
services:

  mssql:
    image: mcr.microsoft.com/mssql/server:${MSSQL_IMAGE_TAG:-2017-latest}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Th3PA55--8zz
    volumes:
      - leaf-mssql:/var/opt/mssql
      - ./src/db/build/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ./src/db/build/configure-db.sh:/usr/local/bin/configure-db.sh:ro
      - ./src/db/build/setup.sql:/opt/mssql/setup.sql:ro

      - ./src/db/build/LeafDB.Schema.sql:/docker-entrypoint-initdb.d/00LeafDB.Schema.sql:ro
      - ./src/db/build/LeafDB.Init.sql:/docker-entrypoint-initdb.d/01LeafDB.Init.sql:ro

      # TODO load LeafDB.GEMs.sql
      # https://github.com/uwrit/leaf-scripts/blob/master/GEMs/LeafDB.GEMs.sql
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    command: /opt/mssql/bin/sqlservr
    networks:
      - internal

  coreapi:
    build:
      context: ./src/server
    depends_on:
      - mssql
    volumes:
      - ./src/server:/app
      - ${KEYS:-./src/server/keys}:/.keys
    environment:
      LEAF_JWT_KEY_PW: ${JWT_KEY_PW}
      LEAF_APP_DB: Server=mssql,1433;Database=LeafDB;uid=sa;Password=Th3PA55--8zz
      LEAF_CLIN_DB: ${CLIN_DB}
    networks:
      - internal

  node:
    build:
      context: ./src/ui-client
    depends_on:
      - coreapi
    volumes:
      - ./src/ui-client:/app

volumes:
  leaf-mssql:

networks:
  # internal network for backing services
  internal:
